language: cpp
sudo: false
os: linux
dist: xenial
compiler: gcc
addons:
  apt:
    packages:
      - libx11-dev
      - libva-dev
install:
  - cmake --version
  - g++ --version
  - JOBS=2
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - cmake --build . -- -j${JOBS}
