language: cpp
sudo: false
os: linux
dist: xenial
compiler: gcc
addons:
  apt:
    packages:
      - libx11-dev
      - libva-dev
      - clang-format-5.0
before_install:
  - cd scripts
  - python3 format.py --check --clang-format=clang-format-5.0
  - cd ..
install:
  - cmake --version
  - g++ --version
  - JOBS=2
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - cmake --build . -- -j${JOBS}
