language: cpp
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      compiler: gcc
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      compiler: clang
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
      compiler: clang-3.8
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      compiler: clang-4.0
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      compiler: clang-5.0
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      compiler: clang-6.0
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
            - g++-6
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      compiler: gcc-6
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libva-dev
            - clang-format-5.0
            - libpng-dev
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      compiler: gcc-7

before_install:
  - cd scripts
  - python3 format.py --check --clang-format=clang-format-5.0
  - cd ..
install:
  - cmake --version
  - g++ --version
  - eval "${MATRIX_EVAL}"
  - scripts/install/install_ubuntu_16_04.sh
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - cmake --build .
