image: Visual Studio 2015

install:
  - cmake --version
  - scripts/install/install_vs2015.ps1

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64"

build_script:
  - cmake --build . -- /m
