image: Visual Studio 2015

install:
  - cmake --version

before_build:
  - ps: scripts\install\install_windows.ps1
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64"

build_script:
  - cmake --build . -- /m
